import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/main-components/Main-navbar";
import { Footer } from "@/components/main-components/Main-footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col  bg-slate-200 antialiased`}
      >
    
        <Navbar   />

        {/* Page Content */}
        <div>
          {children}
        </div>

        {/* Footer */}
        <footer>
          <Footer  />
        </footer>
      </body>
    </html>
  );
}
